In [1]:
import numpy as np
import pandas as pd

In [5]:
a = np.array([1,2,3,4])
type(a)

numpy.ndarray

In [6]:
a

array([1, 2, 3, 4])

In [7]:
a.ndim

1

In [14]:
aa = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
aa

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
aa.ndim

3

In [18]:
aa = np.array([1,2,3])
aa

array([1, 2, 3])

In [19]:
l_tup = np.array([(1,2,3), (3,4,5)])
l_tup

array([[1, 2, 3],
       [3, 4, 5]])

In [20]:
type(l_tup)

numpy.ndarray

In [21]:
l_tup.ndim

2

In [23]:
l_tup.shape

(2, 3)

In [24]:
l_tup.size

6

In [25]:
l_tup.dtype

dtype('int32')

In [27]:
n = np.array(((1,2,3),(2,3,4)))
n

array([[1, 2, 3],
       [2, 3, 4]])

In [28]:
n.itemsize

4

In [33]:
n = np.array((1, 1.3))
n

array([1. , 1.3])

In [34]:
n.itemsize

8

In [35]:
n = np.zeros((2,3))
n

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
n = np.ones((3,3))
n

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
j = np.empty((1,1))
j

array([[1.76127852e-312]])

In [49]:
f = np.arange(0, 30, 5)
f

array([ 0,  5, 10, 15, 20, 25])

In [55]:
f = np.arange(1, 101, 2)
f

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [56]:
r = np.random.random((3,3))
r

array([[0.31408575, 0.87415659, 0.57573986],
       [0.08424326, 0.80389323, 0.03135427],
       [0.50271853, 0.96732061, 0.35680791]])

In [58]:
r = np.random.random((2,3))
r

array([[0.01278367, 0.51673722, 0.06031615],
       [0.61195609, 0.27935705, 0.48121793]])

In [59]:
aa = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
aa

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [63]:
aa.reshape(1,9)
aa

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [64]:
aa.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
aa = np.array([[1,2,3], [4,5,6]])
aa

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
aa.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [67]:
p = np.array([[1,2,3], [4,5,6]])
p

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
q = np.array([[11,22,33], [44,55,66]])
q

array([[11, 22, 33],
       [44, 55, 66]])

In [69]:
p

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
q

array([[11, 22, 33],
       [44, 55, 66]])

In [71]:
pq = np.hstack((p,q))
pq

array([[ 1,  2,  3, 11, 22, 33],
       [ 4,  5,  6, 44, 55, 66]])

In [72]:
pq = np.vstack((p,q))
pq

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 22, 33],
       [44, 55, 66]])

In [110]:
pqs = np.vsplit(pq,2)
pqs

[array([[ 1,  2,  3, 11, 22, 33]]), array([[ 4,  5,  6, 44, 55, 66]])]

In [95]:
pqs = np.vsplit(pq, 2)
pqs

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 22, 33],
        [44, 55, 66]])]

In [96]:
pq

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 22, 33],
       [44, 55, 66]])

In [97]:
pq = np.hstack((p,q))
pq

array([[ 1,  2,  3, 11, 22, 33],
       [ 4,  5,  6, 44, 55, 66]])

In [107]:
pqs = np.hsplit(pq, 6)
pqs

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]]),
 array([[11],
        [44]]),
 array([[22],
        [55]]),
 array([[33],
        [66]])]

In [115]:
pqs = np.hsplit(pq, (3,4))
pqs

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11],
        [44]]),
 array([[22, 33],
        [55, 66]])]

In [118]:
l =np.full((2,3), 11)
l

array([[11, 11, 11],
       [11, 11, 11]])