In [4]:
import pandas as pd
import numpy as np

a1 = np.random.random((3,3))
a1

array([[0.21421579, 0.02290038, 0.44584227],
       [0.3986845 , 0.36782217, 0.62041593],
       [0.05888082, 0.30661851, 0.92665719]])

In [75]:
a1.ndim

2

In [5]:
a2 = np.random.random((3,3))
a2

array([[0.85529083, 0.98760695, 0.76605505],
       [0.32772164, 0.2462016 , 0.00288729],
       [0.85112758, 0.37150162, 0.18023518]])

In [26]:
h_stack = np.hstack((a1,a2))
h_stack

array([[0.21421579, 0.02290038, 0.44584227, 0.85529083, 0.98760695,
        0.76605505],
       [0.3986845 , 0.36782217, 0.62041593, 0.32772164, 0.2462016 ,
        0.00288729],
       [0.05888082, 0.30661851, 0.92665719, 0.85112758, 0.37150162,
        0.18023518]])

In [76]:
h_stack.ndim

2

In [77]:
h_stack.itemsize

8

In [78]:
h_stack.size

18

In [79]:
h_stack.shape

(3, 6)

In [10]:
v_stk = np.vstack((a1,a2))
v_stk

array([[0.21421579, 0.02290038, 0.44584227],
       [0.3986845 , 0.36782217, 0.62041593],
       [0.05888082, 0.30661851, 0.92665719],
       [0.85529083, 0.98760695, 0.76605505],
       [0.32772164, 0.2462016 , 0.00288729],
       [0.85112758, 0.37150162, 0.18023518]])

In [23]:
v_stk.shape

(6, 3)

In [80]:
v_stk.ndim

2

In [81]:
v_stk.itemsize

8

In [83]:
v_stk.size

18

In [45]:
# again original situation stack if (h_stack, 2) -- 2 array 2 row
# if 3 then 3 row - array
h_spl = np.hsplit(h_stack, 6) 
h_spl
# h_stack

[array([[0.21421579, 0.02290038, 0.44584227, 0.85529083, 0.98760695,
         0.76605505],
        [0.3986845 , 0.36782217, 0.62041593, 0.32772164, 0.2462016 ,
         0.00288729],
        [0.05888082, 0.30661851, 0.92665719, 0.85112758, 0.37150162,
         0.18023518]])]

In [46]:
h_spl = np.hsplit(h_stack, 3) 
h_spl

[array([[0.21421579, 0.02290038],
        [0.3986845 , 0.36782217],
        [0.05888082, 0.30661851]]),
 array([[0.44584227, 0.85529083],
        [0.62041593, 0.32772164],
        [0.92665719, 0.85112758]]),
 array([[0.98760695, 0.76605505],
        [0.2462016 , 0.00288729],
        [0.37150162, 0.18023518]])]

In [47]:
h_spl = np.hsplit(h_stack, 2) 
h_spl

[array([[0.21421579, 0.02290038, 0.44584227],
        [0.3986845 , 0.36782217, 0.62041593],
        [0.05888082, 0.30661851, 0.92665719]]),
 array([[0.85529083, 0.98760695, 0.76605505],
        [0.32772164, 0.2462016 , 0.00288729],
        [0.85112758, 0.37150162, 0.18023518]])]

In [48]:
h_stack

array([[0.21421579, 0.02290038, 0.44584227, 0.85529083, 0.98760695,
        0.76605505],
       [0.3986845 , 0.36782217, 0.62041593, 0.32772164, 0.2462016 ,
        0.00288729],
       [0.05888082, 0.30661851, 0.92665719, 0.85112758, 0.37150162,
        0.18023518]])

In [60]:
#vertical split - lenth of vertical is 3 so we can split array till 3 only 
v_spl = np.vsplit(h_stack, 3)
v_spl

[array([[0.21421579, 0.02290038, 0.44584227, 0.85529083, 0.98760695,
         0.76605505]]),
 array([[0.3986845 , 0.36782217, 0.62041593, 0.32772164, 0.2462016 ,
         0.00288729]]),
 array([[0.05888082, 0.30661851, 0.92665719, 0.85112758, 0.37150162,
         0.18023518]])]

In [62]:
v_stk

array([[0.21421579, 0.02290038, 0.44584227],
       [0.3986845 , 0.36782217, 0.62041593],
       [0.05888082, 0.30661851, 0.92665719],
       [0.85529083, 0.98760695, 0.76605505],
       [0.32772164, 0.2462016 , 0.00288729],
       [0.85112758, 0.37150162, 0.18023518]])

In [65]:
h_spl = np.hsplit(v_stk, 3)
h_spl

[array([[0.21421579],
        [0.3986845 ],
        [0.05888082],
        [0.85529083],
        [0.32772164],
        [0.85112758]]),
 array([[0.02290038],
        [0.36782217],
        [0.30661851],
        [0.98760695],
        [0.2462016 ],
        [0.37150162]]),
 array([[0.44584227],
        [0.62041593],
        [0.92665719],
        [0.76605505],
        [0.00288729],
        [0.18023518]])]

In [72]:
h_spl = np.vsplit(v_stk, (1,2))
h_spl

[array([[0.21421579, 0.02290038, 0.44584227]]),
 array([[0.3986845 , 0.36782217, 0.62041593]]),
 array([[0.05888082, 0.30661851, 0.92665719],
        [0.85529083, 0.98760695, 0.76605505],
        [0.32772164, 0.2462016 , 0.00288729],
        [0.85112758, 0.37150162, 0.18023518]])]

In [74]:
h_spl = np.vsplit(v_stk, (2,1))
h_spl

[array([[0.21421579, 0.02290038, 0.44584227],
        [0.3986845 , 0.36782217, 0.62041593]]),
 array([], shape=(0, 3), dtype=float64),
 array([[0.3986845 , 0.36782217, 0.62041593],
        [0.05888082, 0.30661851, 0.92665719],
        [0.85529083, 0.98760695, 0.76605505],
        [0.32772164, 0.2462016 , 0.00288729],
        [0.85112758, 0.37150162, 0.18023518]])]